name: datapipe
channels:
  - bioconda
  - conda-forge
  - defaults
  - cov-ert
dependencies:
  - biopython>=1.74
  - minimap2>=2.17
  - pip=19.3.1
  - python>=3.7
  - snakemake-minimal>=6.4.1,<=6.8.0
  - gofasta<=0.0.4
  - pysam==0.16.0.1
  - usher>=0.3.2
  - coreutils>=8.25
  - nextflow
  - s3cmd
  - smart_open
  - pip:
      - ftfy
      - geopandas
      - git+https://github.com/cov-lineages/pangolin.git
      - git+https://github.com/cov-lineages/pangolin-data.git
      - git+https://github.com/cov-ert/fastafunk.git
      - git+https://github.com/cov-lineages/constellations.git
      - git+https://github.com/cov-lineages/scorpio.git


